FROM node:10.9.0-jessie

WORKDIR /home/customer-website-frontend

COPY internals internals
COPY package.json package.json
COPY yarn.lock yarn.lock

RUN yarn install

COPY . .

ARG API_ENV="staging"

ENV API_ENV=$API_ENV

RUN yarn build
